#      __  ___           ____
#     /  |/  /___ ______/ __ )____ _____  _____
#    / /|_/ / __ `/ ___/ __  / __ `/ __ \/ ___/
#   / /  / / /_/ / /__/ /_/ / /_/ / / / (__  )
#  /_/  /_/\__,_/\___/_____/\__,_/_/ /_/____/
# By RLOAD Labs (Developed by md_4)
# Discord: https://discord.gg/JcAy9fS75G

Version: '${project.version}'

############-License-############
License-Key: ""
#################################

####-Lang-####
#  It / En  #
Lang: "It"
##############

#######-MySQL-#######
Host: "127.0.0.1"
Port: "3306"
DataBase: ""
UserName: ""
Password: ""
#####################
